### ISSUE TITLE
Local or global sensitivity with MAX_CONTRIB?

### ISSUE THREAD

**Issue by giulianopietoso-apheris** [opendifferentialprivacy/smartnoise-sdk#308]
I am wondering whether the privacy mechanism in the library is for local sensitivity as defined by [Nissm et al. (Nissim, Kobbi, Sofya Raskhodnikova, and Adam Smith. "Smooth sensitivity and sampling in private data analysis." Proceedings of the thirty-ninth annual ACM symposium on Theory of computing. 2007)](http://www.cse.psu.edu/~sxr48/pubs/smooth-sensitivity-stoc.pdf) or global sensitivity. 

Concretely, do we set the **max_contrib** parameter to what we measure for our specific view (or database) or to the maximum possible in general? This is crucial especially in situations where we prepare a view upfront to avoid joins in the query to Smartnoise.

Thank you.

**Comment by joshua-oss** [comment]
The max_contrib is intended to be the maximum number of times that the user *could* appear.  Note that, by default, we will reservoir sample to enforce this number, so (e.g.) if your view returns too many rows with the same user, the result will be that some records are randomly dropped.  So the impact will be against utility rather than privacy.  The best utility trade-off between smaller and larger user contribution may depend on the database.

Note that this pattern is best-suited for cases where the user identifier is part of every join key, and where user contributions can be disjointly partitioned across grouping keys.

As we are thinking about how to re-introduce support for JOINs, we welcome your feedback on the styles of JOINs that are most important to you.  Here are examples of 4 categories of (non-JOIN) queries, which all affect user contribution in different ways.  All 4 of these patterns are more likely to occur when using JOINS:

We can categorize queries based on two parameters that describe the user contribution: 
* tau – The maximum number of times a user can appear in each partition
* Delta – The maximum number of partitions a user can appear in 

Here are some examples of queries, characterized by user contributions: 

**tau = 1, Delta = 1**  

`SELECT AVG(income) FROM PUMS GROUP BY married`

This type of query is typical for row-privacy, common in social science and other tidy  datasets. 

**tau = *, Delta = 1**  

`SELECT Region, SUM(TotalPrice) FROM CustomerOrder GROUP BY  Region` 

In this query, each user is assigned to only one region, so each user can appear in only  one partition. However, each user may have multiple orders. 

**tau = 1, Delta = ***  

`SELECT ProductCategory, COUNT(DISTINCT CustomerID) FROM Order `

In this query, each user may have purchased products from multiple categories, but  each user can impact the count of each bin by at most 1. 

**tau = *, Delta = ***  

`SELECT url, COUNT(DISTINCT User), SUM(DwellTime) `

This query can be used to rank web sites by unique users and engagement time. Each  user may browse several web sites, and the SUM of DwellTime may include many visits  from the same user to a single web site. 

The SQL API has limited ability to infer that a query conforms to specific tau and Delta bounds, by validating the form of the query and using information from metadata. In  many cases, the validator will not be able to infer these bounds, or may need to assume  bounds that are too large. 

The SQL API is capable of reservoir sampling to enforce tau, and can also sample to  enforce the maximum number of times a user can appear across all partitions, but it is  not straightforward to enforce a bound on Delta. In practice, Delta is often either 1  (due to query semantics) or is unbounded, being as large as the number of partitions.

**Comment by giulianopietoso-apheris** [comment]
Thank you very much for the explanation and insights. They were really helpful for us to continue working with the library.
