### ISSUE TITLE
Sensitivity calculation of a sum expression is inconsistent

### ISSUE THREAD

**Issue by gregaw** [opendifferentialprivacy/smartnoise-sdk#319]
class ArithmeticExpression calculates the sensitivity of an expression x+y as max (x.sens, y.sens) and sensitivity of 2*x as 2*x.sens.

But then we get 2*x.sens=sens(2*x) <> sens(x+x)=max(x.sens, x.sens)=x.sens.

**Comment by joshua-oss** [comment]
Oops, that's a bug!  

Note that PrivateReader.execute() currently prohibits aggregations around arithmetic expressions.  For example, queries like `SELECT SUM(income + income)` or `SELECT SUM(2 * income)` will raise ValueError with message *"We don't support aggregation over expressions"*.  Calling like `SUM(income) + SUM(income)` or `SUM(income) * 2` is supported, and the sensitivities are computed correctly when generating noise.  

However, the sensitivity computation for addition was clearly wrong, and would've caused problems when we enable inner expressions in the future.  Thank you for reporting this!

Fixed in PR #320.  We will close this bug after the fix is deployed to PyPi.

**Comment by gregaw** [comment]
Thanks!
You're right - that part of code isn't executed.
I just stumbled upon it when statically analysing the sensitivity implementation in smartnoise, so thought I would mention that.
